# Site Configuration
url: ""

site_profiles:
  title: GolmokDaeBBang
  email: your-email@example.com
  description: >- # this means to ignore newlines until "baseurl:"
  baseurl: "" # the subpath of your site, e.g. /blog
  github_username:  jekyll


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
theme: minima
plugins:
  - jekyll-feed
